### ISSUE TITLE
Why do I have to do flutter create . to build?

### ISSUE THREAD

**Issue by sgehrman** [creativecreatorormaybenot/clock#1]
Just wondering why it's not simple to build and run?

I had to run flutter create .

Got this error: 
AndroidManifest.xml could not be found.
Please check /home/steve/google/clock/canvas_clock/android/AndroidManifest.xml for errors.
No application found for TargetPlatform.android_x64.
Is your project missing an android/AndroidManifest.xml?
Consider running "flutter create ." to create one.

**Comment by creativecreatorormaybenot** [comment]
I am glad you took a look at the project and asked 😃 

In this project, I excluded the `ios`, `android`, and `web` directories (as part of preparing the clock for submission, see [Getting Started here](https://flutter.dev/clock)). Consequently, `flutter create .` is required to generate these before you can run the project. Additionally, it would get any missing packages (if any were used 😄 ).
This **saves size** and also **ensures longer compatibility** because `flutter create .` will always add the latest platform setup.

I did not think that the question would come up. Now that you asked, I will include it in the README. See the commit linked below.

**Comment by sgehrman** [comment]
Thanks for the response and adding it to the readme.
